# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

users = User.create([{name: 'josh', email: 'josh@email.com', password: 'password'}, {name: 'mike', email: 'mike@email.com', password: 'password'}])
Deck.create(name: "Grixis Control", user: User.find_by(:name => "josh"))
Card.create(name: "The Scarab God", quantity: "1", deck: users.first.decks.first)
Card.create(name: "Torrential Gearhulk", quantity: "3", deck: users.first.decks.first)
Card.create(name: "Chandra, Torch of Defiance", quantity: "2", deck: users.first.decks.first)
Card.create(name: "Magma Spray", quantity: "2", deck: users.first.decks.first)
Card.create(name: "Abrade", quantity: "3", deck: users.first.decks.first)
Card.create(name: "Harnessed Lightning", quantity: "2", deck: users.first.decks.first)
Card.create(name: "Essence Scatter", quantity: "2", deck: users.first.decks.first)
Card.create(name: "Harnessed Lightning", quantity: "2", deck: users.first.decks.first)
Card.create(name: "Negate", quantity: "1", deck: users.first.decks.first)
Card.create(name: "Disallow", quantity: "3", deck: users.first.decks.first)
Card.create(name: "Doomfall", quantity: "2", deck: users.first.decks.first)
Card.create(name: "Sweltering Suns", quantity: "2", deck: users.first.decks.first)
Card.create(name: "Glimmer of Genius", quantity: "4", deck: users.first.decks.first)
Card.create(name: "Vraska's Contempt", quantity: "4", deck: users.first.decks.first)
Card.create(name: "Commit // Memory", quantity: "1", deck: users.first.decks.first)
Card.create(name: "Search for Azcanta", quantity: "2", deck: users.first.decks.first)
Card.create(name: "Aether Hub", quantity: "4", deck: users.first.decks.first)
Card.create(name: "Canyon Slough", quantity: "3", deck: users.first.decks.first)
Card.create(name: "Dragonskull Summit", quantity: "4", deck: users.first.decks.first)
Card.create(name: "Drowned Catacomb", quantity: "4", deck: users.first.decks.first)
Card.create(name: "Fetid Pools", quantity: "3", deck: users.first.decks.first)
Card.create(name: "Island", quantity: "2", deck: users.first.decks.first)
Card.create(name: "Mountain", quantity: "1", deck: users.first.decks.first)
Card.create(name: "Spirebluff Canal", quantity: "2", deck: users.first.decks.first)
Card.create(name: "Sulfur Falls", quantity: "2", deck: users.first.decks.first)
Card.create(name: "Swamp", quantity: "1", deck: users.first.decks.first)


Deck.create(name: "Mono-Green", user: User.find_by(:name => "josh"))
Card.create(name: "jadelight ranger", quantity: "4", deck: users.first.decks.last)
Card.create(name: "blossoming defense", quantity: "4", deck: users.first.decks.last)
Card.create(name: "ghalta", quantity: "2", deck: users.first.decks.last)
Card.create(name: "rhonas' monument", quantity: "4", deck: users.first.decks.last)

Deck.create(name: "Mono-Red", user: User.find_by(:name => "mike"))
Card.create(name: "lightning strike", quantity: "4", deck: users.last.decks.first)
Card.create(name: "glorybringer", quantity: "3", deck: users.last.decks.first)
Card.create(name: "shock", quantity: "2", deck: users.last.decks.first)
Card.create(name: "soul-scar mage", quantity: "4", deck: users.last.decks.first)

Deck.create(name: "Burn", user: User.find_by(:name => "mike"))
Card.create(name: "lightning bolt", quantity: "4", deck: users.last.decks.last)
Card.create(name: "boros charm", quantity: "4", deck: users.last.decks.last)
Card.create(name: "lava spike", quantity: "4", deck: users.last.decks.last)
Card.create(name: "goblin guide", quantity: "4", deck: users.last.decks.last)
